version: '3'

tasks:
  run:
    cmds:
      - go run cmd/main.go
  test:
    cmds:
      - go clean -testcache
      - go test -cover ./...
  bench:
    cmds:
      - go clean -testcache
      - go test ./... -bench=. -benchmem
